[build]
  publish = "dist/browser"
  command = "npm run build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/callmebot/*"
  to = "https://api.callmebot.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/send-whatsapp"
  to = "/.netlify/functions/send-whatsapp"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.csr.html"
  status = 200
